swagger: '2.0'
info:
  title: Social API
  version: "0.1"
  description: Social network API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /ackFriendRequest/:
    post:
      tags : [ AcknowledgeFriendRequest ]
      operationId : app.ackFriendRequest
      summary : User acknowledging a friend request
      parameters : 
        - $ref : '#/parameters/friendBody'
      responses : 
        200 :
          description : OK
        500 : 
          description : Internal server error

  /sendFriendRequest/:
    post:
      tags : [ FriendRequest ]
      operationId : app.sendFriendRequest
      summary : Sending a friend request
      parameters : 
        - $ref : '#/parameters/friendRequestBody'
      responses : 
        200:
          description : OK
        500:
          description : Internal server error

  /sendMsg/:
    post:
      tags : [ Message ]
      operationId : app.sendMessage
      summary : Sending a message
      parameters:
        - $ref : '#/parameters/msgBody'
      responses : 
        200:
          description : Message successfully sent and saved
        500:
          description : Internal server error
  
parameters:
  msgBody :
    name : msgBody
    description : The body of the message
    in : body
    schema :
      required :
        - fromUserId
        - toUserId
        - text
      properties : 
        fromUserId :
          type : integer
        toUserId :
          type : integer
        text : 
          type : string

  friendRequestBody:
    name : friendRequestBody
    description : The body for a friend request
    in : body
    schema:
      required :
        - fromUserId
        - toUserId
      properties:
        fromUserId :
          type : integer
        toUserId :
          type : integer

  friendBody:
    name : friendBody
    description : This is used when a user accepts/rejects a friend request
    in : body
    schema : 
      required :
        