swagger: '2.0'
info:
  title: Social API
  version: "0.1"
  description: Social microservice API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /friends/{user_id}:
    get:
      tags: [ User friends ]
      operationId: app.get_all_user_friends
      summary: Testing endpoint
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return users list
        404:
          description: Does not exist

  /timeline/{user_id}:
    get:
      tags: [ User timeline ]
      operationId: app.get_user_timeline
      summary: Testing endpoint
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user feed
        404:
          description: Does not exists

  /feed/{user_id}:
    get:
      tags: [ User feed ]
      operationId: app.get_global_feed
      summary: Testing endpoint
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return global feed
        404:
          description: Does not exists

  /requests/{user_id}:
    get:
      tags: [ User friend requests ]
      operationId: app.get_all_user_friend_requests
      summary: Testing endpoint
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return friend requests
        404:
          description: Does not exists


parameters:
  user_id:
    name: user_id
    description: User unique id
    in: path
    type: integer
    required: true