"""empty message

Revision ID: 13b9589d4317
Revises: 1945e1028ec1
Create Date: 2021-04-18 11:19:15.240559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b9589d4317'
down_revision = '1945e1028ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('isCycleService', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    op.drop_table('location')
    # ### end Alembic commands ###
