"""empty message

Revision ID: 1945e1028ec1
Revises: 3bdfb95ecb10
Create Date: 2021-04-17 11:45:32.808581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1945e1028ec1'
down_revision = '3bdfb95ecb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycled_routes', sa.Column('cycledTime', sa.Float(), nullable=False))
    op.add_column('cycled_routes', sa.Column('userWeight', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycled_routes', 'userWeight')
    op.drop_column('cycled_routes', 'cycledTime')
    # ### end Alembic commands ###
