"""empty message

Revision ID: 3bdfb95ecb10
Revises: 9a56f8ae97ec
Create Date: 2021-04-17 11:13:32.663851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdfb95ecb10'
down_revision = '9a56f8ae97ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('latFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('latTo', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngTo', sa.String(), nullable=False))
    op.drop_column('route', 'lng')
    op.drop_column('route', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('lng', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('route', 'lngTo')
    op.drop_column('route', 'lngFrom')
    op.drop_column('route', 'latTo')
    op.drop_column('route', 'latFrom')
    # ### end Alembic commands ###
