"""empty message

Revision ID: 406596f7dde3
Revises: fa5c6aa56844
Create Date: 2021-04-16 19:40:55.351991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406596f7dde3'
down_revision = 'fa5c6aa56844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'createdOn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('createdOn', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
