"""empty message

Revision ID: 49d0930c6b28
Revises: 6a39a2507104
Create Date: 2021-04-26 14:02:26.660064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d0930c6b28'
down_revision = '6a39a2507104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'createdOn',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('cycled_routes', sa.Column('cycledTime', sa.Float(), nullable=False))
    op.add_column('cycled_routes', sa.Column('userWeight', sa.String(), nullable=False))
    op.alter_column('posts', 'createdOn',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('route', sa.Column('latFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('latTo', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngTo', sa.String(), nullable=False))
    op.drop_column('route', 'lng')
    op.drop_column('route', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('lng', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('route', 'lngTo')
    op.drop_column('route', 'lngFrom')
    op.drop_column('route', 'latTo')
    op.drop_column('route', 'latFrom')
    op.alter_column('posts', 'createdOn',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('cycled_routes', 'userWeight')
    op.drop_column('cycled_routes', 'cycledTime')
    op.alter_column('comments', 'createdOn',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
