"""empty message

Revision ID: 811bea498c46
Revises: 
Create Date: 2021-05-11 14:11:47.597627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811bea498c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request',
    sa.Column('fromUserId', sa.BigInteger(), nullable=False),
    sa.Column('toUserId', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'CANCELED', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('fromUserId', 'toUserId')
    )
    op.create_table('friends',
    sa.Column('user1Id', sa.BigInteger(), nullable=False),
    sa.Column('user2Id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user1Id', 'user2Id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('isCycleService', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('fromUserId', sa.BigInteger(), nullable=False),
    sa.Column('toUserId', sa.BigInteger(), nullable=False),
    sa.Column('dateSent', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fromUserId', 'toUserId', 'dateSent')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lngFrom', sa.String(), nullable=False),
    sa.Column('latFrom', sa.String(), nullable=False),
    sa.Column('lngTo', sa.String(), nullable=False),
    sa.Column('latTo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.Integer(), nullable=False),
    sa.Column('partyCreatorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycled_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('distanceTraveled', sa.String(), nullable=False),
    sa.Column('userWeight', sa.String(), nullable=False),
    sa.Column('cycledTime', sa.Float(), nullable=False),
    sa.Column('caloriesBurned', sa.BigInteger(), nullable=True),
    sa.Column('route', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id', 'userId')
    )
    op.create_table('cycle_party_member',
    sa.Column('partyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['partyId'], ['cycle_party.id'], ),
    sa.PrimaryKeyConstraint('partyId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycle_party_member')
    op.drop_table('cycled_routes')
    op.drop_table('cycle_party')
    op.drop_table('comments')
    op.drop_table('route')
    op.drop_table('posts')
    op.drop_table('messages')
    op.drop_table('location')
    op.drop_table('friends')
    op.drop_table('friend_request')
    # ### end Alembic commands ###
