"""empty message

Revision ID: 921ba6996a1a
Revises: ef2123f8e42c
Create Date: 2021-04-16 16:09:20.817851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921ba6996a1a'
down_revision = 'ef2123f8e42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'dateSent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dateSent', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
