"""empty message

Revision ID: 9a56f8ae97ec
Revises: 406596f7dde3
Create Date: 2021-04-16 19:41:10.540463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a56f8ae97ec'
down_revision = '406596f7dde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('createdOn', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'createdOn')
    # ### end Alembic commands ###
