"""empty message

Revision ID: b3114edecb20
Revises: 869a4cf2cd88
Create Date: 2021-04-18 23:00:24.048759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3114edecb20'
down_revision = '869a4cf2cd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('isCycleService', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comments', 'createdOn',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('cycled_routes', sa.Column('cycledTime', sa.Float(), nullable=False))
    op.add_column('cycled_routes', sa.Column('userWeight', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('posts', 'createdOn',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('route', sa.Column('latFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('latTo', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngFrom', sa.String(), nullable=False))
    op.add_column('route', sa.Column('lngTo', sa.String(), nullable=False))
    op.drop_column('route', 'lng')
    op.drop_column('route', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('route', sa.Column('lng', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('route', 'lngTo')
    op.drop_column('route', 'lngFrom')
    op.drop_column('route', 'latTo')
    op.drop_column('route', 'latFrom')
    op.alter_column('posts', 'createdOn',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('posts', 'image')
    op.drop_column('cycled_routes', 'userWeight')
    op.drop_column('cycled_routes', 'cycledTime')
    op.alter_column('comments', 'createdOn',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('location')
    # ### end Alembic commands ###
