"""empty message

Revision ID: d8ce1648831e
Revises: 921ba6996a1a
Create Date: 2021-04-16 16:09:38.260049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ce1648831e'
down_revision = '921ba6996a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dateSent', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'dateSent')
    # ### end Alembic commands ###
