"""empty message

Revision ID: eb2d1ca7c810
Revises: 
Create Date: 2021-04-19 00:12:01.657283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2d1ca7c810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('isCycleService', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    op.drop_table('location')
    # ### end Alembic commands ###
