"""empty message

Revision ID: fa5c6aa56844
Revises: 8753d6061c06
Create Date: 2021-04-16 19:39:43.777349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5c6aa56844'
down_revision = '8753d6061c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('createdOn', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'createdOn')
    # ### end Alembic commands ###
