"""empty message

Revision ID: ffa4038b5a56
Revises: 811bea498c46
Create Date: 2021-05-11 16:37:10.376536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa4038b5a56'
down_revision = '811bea498c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'userId',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'userId',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
